<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="codex" nsURI="http://www.example.org/modelDecode" nsPrefix="codex">
  <eClassifiers xsi:type="ecore:EClass" name="CodingExperiment" eSuperTypes="#//aux/Nameable #//aux/Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="groups" upperBound="-1"
        eType="#//taskDescription/ExecutionGroups" containment="true"/>
  </eClassifiers>
  <eSubpackages name="taskDescription" nsURI="taskDescription" nsPrefix="taskDescription">
    <eClassifiers xsi:type="ecore:EClass" name="AbstractTask" abstract="true" eSuperTypes="#//aux/Nameable #//aux/Identifiable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//taskDescription/AbstractTask"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" upperBound="-1"
          eType="#//taskDescription/constraint/Constraint" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="observedata" upperBound="-1"
          eType="#//taskDescription/dataTrack/ObserveData" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExecutionGroups">
      <eStructuralFeatures xsi:type="ecore:EReference" name="execution" ordered="false"
          lowerBound="1" upperBound="-1" eType="#//taskDescription/AbstractTask" containment="true"/>
    </eClassifiers>
    <eSubpackages name="dataTrack" nsURI="dataTrack" nsPrefix="dataTrack">
      <eClassifiers xsi:type="ecore:EEnum" name="TrackEnum">
        <eLiterals name="TIME"/>
        <eLiterals name="ARTIFACT" value="1"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ObserveData" abstract="true" interface="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="DataFromAction" eSuperTypes="#//taskDescription/dataTrack/ObserveData">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="track" lowerBound="1"
            eType="#//taskDescription/dataTrack/TrackEnum"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="moment" lowerBound="1"
            eType="#//taskDescription/dataTrack/MomentEnum"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DataFromQuestionnaire" eSuperTypes="#//taskDescription/dataTrack/ObserveData">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="allocation" eType="#//taskDescription/dataTrack/AllocationEnum"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="questionnaire" eType="#//artifact/AbstractQuestionnaire"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="MomentEnum">
        <eLiterals name="FILE_EDITING"/>
        <eLiterals name="FILE_EXECUTION" value="1"/>
        <eLiterals name="IDE_ACTIVITY" value="2"/>
        <eLiterals name="TEST_EXECUTION" value="3"/>
        <eLiterals name="COMPLETED_TASK" value="4"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="AllocationEnum">
        <eLiterals name="BEFORE"/>
        <eLiterals name="AFTER" value="1"/>
        <eLiterals name="WHILE" value="2"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="order" nsURI="order" nsPrefix="order">
      <eClassifiers xsi:type="ecore:EClass" name="ComposedTask" abstract="true" eSuperTypes="#//taskDescription/AbstractTask"/>
      <eClassifiers xsi:type="ecore:EClass" name="OrderedExecution" eSuperTypes="#//taskDescription/order/ComposedTask">
        <eStructuralFeatures xsi:type="ecore:EReference" name="children" lowerBound="1"
            upperBound="-1" eType="#//taskDescription/AbstractTask" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RandomExecution" eSuperTypes="#//taskDescription/order/ComposedTask">
        <eStructuralFeatures xsi:type="ecore:EReference" name="children" ordered="false"
            lowerBound="1" upperBound="-1" eType="#//taskDescription/AbstractTask"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="CodingTask" eSuperTypes="#//taskDescription/AbstractTask">
        <eStructuralFeatures xsi:type="ecore:EReference" name="depends" upperBound="-1"
            eType="#//taskDescription/order/CodingTask"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="constraint" nsURI="constraint" nsPrefix="constraint">
      <eClassifiers xsi:type="ecore:EClass" name="Constraint" abstract="true" interface="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="TimeConstraint" eSuperTypes="#//taskDescription/constraint/Constraint">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="executionWindow" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Date"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="deadline" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//DateTime"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="CodingToolConstraint" eSuperTypes="#//taskDescription/constraint/Constraint">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="RequiredCharac" upperBound="-1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="notAllowedCharac" upperBound="-1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TestConstraint" eSuperTypes="#//taskDescription/constraint/Constraint"/>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="aux" nsURI="aux" nsPrefix="aux">
    <eClassifiers xsi:type="ecore:EClass" name="Nameable" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Identifiable" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementId" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
          iD="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="artifact" nsURI="artifact" nsPrefix="artifact">
    <eClassifiers xsi:type="ecore:EClass" name="ProvidedArtifacts">
      <eStructuralFeatures xsi:type="ecore:EReference" name="abstractartifact" upperBound="-1"
          eType="#//artifact/AbstractArtifact" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractArtifact" abstract="true"
        interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArtifactContainer" abstract="true"
        eSuperTypes="#//artifact/AbstractArtifact"/>
    <eClassifiers xsi:type="ecore:EClass" name="SimpleContainer" eSuperTypes="#//artifact/ArtifactContainer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
          eType="#//artifact/SimpleArtifact" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Project" eSuperTypes="#//artifact/ArtifactContainer">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="facet" ordered="false"
          lowerBound="1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
          eType="#//artifact/SourceCode" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="libraries" upperBound="-1"
          eType="#//artifact/LIbrary" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ordinaryFiles" upperBound="-1"
          eType="#//artifact/OrdinaryFile" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SimpleArtifact" abstract="true" eSuperTypes="#//artifact/AbstractArtifact">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Base64Binary"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filePath" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="directoryStructure" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SourceCode" eSuperTypes="#//artifact/SimpleArtifact">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LIbrary" eSuperTypes="#//artifact/SimpleArtifact"/>
    <eClassifiers xsi:type="ecore:EClass" name="Document" eSuperTypes="#//artifact/SimpleArtifact">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OrdinaryFile" eSuperTypes="#//artifact/SimpleArtifact"/>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractQuestionnaire" abstract="true"
        interface="true" eSuperTypes="#//artifact/AbstractArtifact"/>
    <eClassifiers xsi:type="ecore:EClass" name="PhysicalQuestionnarie" eSuperTypes="#//artifact/AbstractQuestionnaire #//artifact/Document"/>
    <eSubpackages name="questionnarie" nsURI="questionnarie" nsPrefix="questionnarie">
      <eClassifiers xsi:type="ecore:EClass" name="LogicalQuestionnarie" eSuperTypes="#//artifact/AbstractQuestionnaire">
        <eStructuralFeatures xsi:type="ecore:EReference" name="items" lowerBound="1"
            upperBound="-1" eType="#//artifact/questionnarie/AbstractComponent" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AbstractComponent" abstract="true"
          eSuperTypes="#//artifact/questionnarie/Labelable">
        <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
            eType="#//artifact/questionnarie/Constraint" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="#//artifact/questionnarie/AbstractComponent">
        <eStructuralFeatures xsi:type="ecore:EReference" name="children" lowerBound="1"
            upperBound="-1" eType="#//artifact/questionnarie/AbstractComponent" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Question" abstract="true" interface="true"
          eSuperTypes="#//artifact/questionnarie/AbstractComponent"/>
      <eClassifiers xsi:type="ecore:EClass" name="TextAnswer" eSuperTypes="#//artifact/questionnarie/Question">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="isTextBox" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
            defaultValueLiteral="false"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="MultiChoiceQuestion" eSuperTypes="#//artifact/questionnarie/Question">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"
            defaultValueLiteral="1"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"
            defaultValueLiteral="1"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="choices" lowerBound="2"
            upperBound="-1" eType="#//artifact/questionnarie/Choice" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Choice" eSuperTypes="#//artifact/questionnarie/Labelable"/>
      <eClassifiers xsi:type="ecore:EClass" name="Constraint" abstract="true" interface="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="AppendableQuestion" eSuperTypes="#//artifact/questionnarie/Constraint">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultQuantity" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"
            defaultValueLiteral="1"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DependentQuestion" eSuperTypes="#//artifact/questionnarie/Constraint">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="expectedAnswer" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="question" lowerBound="1"
            eType="#//artifact/questionnarie/Question"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Labelable" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="content" ordered="false"
            lowerBound="1" upperBound="-1" eType="#//artifact/questionnarie/Content"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Content">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
