<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="decode" nsURI="http://www.example.org/modelDecode" nsPrefix="modelDecode">
  <eClassifiers xsi:type="ecore:EClass" name="CodingExperiment" eSuperTypes="#//aux/Nameable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="task" lowerBound="1" eType="#//taskDescription/ExecutionDerivations"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedArtefacts" lowerBound="1"
        eType="#//artifacts/ProvidedArtefacts" containment="true"/>
  </eClassifiers>
  <eSubpackages name="taskDescription" nsURI="taskDescription" nsPrefix="taskDescription">
    <eClassifiers xsi:type="ecore:EClass" name="ModeledTask" abstract="true" eSuperTypes="#//aux/Nameable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="restriction" eType="#//taskDescription/ModeledRestrictions"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="measurements" upperBound="-1"
          eType="#//taskDescription/Measurement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Sequencial" eSuperTypes="#//taskDescription/ComposedTask">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
          eType="#//taskDescription/ModeledTask" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Random" eSuperTypes="#//taskDescription/ComposedTask">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" ordered="false"
          upperBound="-1" eType="#//taskDescription/ModeledTask" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComposedTask" abstract="true" eSuperTypes="#//taskDescription/ModeledTask"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExperimentalTask" eSuperTypes="#//taskDescription/ModeledTask">
      <eStructuralFeatures xsi:type="ecore:EReference" name="depends" upperBound="-1"
          eType="#//taskDescription/ExperimentalTask"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requires" upperBound="-1"
          eType="#//artifacts/AbstractArtifact"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Restriction" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="QuestionnaireMeasurement" eSuperTypes="#//taskDescription/Measurement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="placement" eType="#//taskDescription/PlacementType"
          defaultValueLiteral="Before"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="questionnaire" eType="#//artifacts/QuestionnaireInner"
          eOpposite="#//artifacts/QuestionnaireInner/placementquestionnaire"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="PlacementType">
      <eLiterals name="After"/>
      <eLiterals name="Before" value="1"/>
      <eLiterals name="During" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExecutionDerivations">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" lowerBound="1"
          upperBound="-1" eType="#//taskDescription/ModeledTask" containment="true">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="wildcards" value=""/>
          <details key="name" value=""/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TimeRestriction" eSuperTypes="#//taskDescription/Restriction">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeFrame" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="deadline" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//DateTime"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SpecficRestriction" abstract="true"
        eSuperTypes="#//taskDescription/Restriction"/>
    <eClassifiers xsi:type="ecore:EClass" name="EclipseRetriction" eSuperTypes="#//taskDescription/SpecficRestriction">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="forbiden" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OtherRestriction" eSuperTypes="#//taskDescription/Restriction">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModeledRestrictions">
      <eStructuralFeatures xsi:type="ecore:EReference" name="children" lowerBound="1"
          upperBound="-1" eType="#//taskDescription/Restriction" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Measurement" abstract="true"/>
    <eSubpackages name="measurements" nsURI="measurements" nsPrefix="measurements">
      <eClassifiers xsi:type="ecore:EClass" name="AutomaticMeasurement" abstract="true"
          eSuperTypes="#//taskDescription/Measurement">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="log" upperBound="2"
            eType="#//taskDescription/measurements/LogType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Actions" abstract="true" eSuperTypes="#//taskDescription/measurements/AutomaticMeasurement"/>
      <eClassifiers xsi:type="ecore:EClass" name="FinalTask" eSuperTypes="#//taskDescription/measurements/AutomaticMeasurement"/>
      <eClassifiers xsi:type="ecore:EClass" name="Edition" eSuperTypes="#//taskDescription/measurements/Actions"/>
      <eClassifiers xsi:type="ecore:EClass" name="Execution" eSuperTypes="#//taskDescription/measurements/Actions"/>
      <eClassifiers xsi:type="ecore:EClass" name="AnyAction" eSuperTypes="#//taskDescription/measurements/Actions"/>
      <eClassifiers xsi:type="ecore:EClass" name="TestExecution" eSuperTypes="#//taskDescription/measurements/Execution">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="observePassedTest"
            eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="LogType">
        <eLiterals name="LogTime"/>
        <eLiterals name="LogArtifact" value="1"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="artifacts" nsURI="artifacts" nsPrefix="artifacts">
    <eClassifiers xsi:type="ecore:EClass" name="ProvidedArtefacts">
      <eStructuralFeatures xsi:type="ecore:EReference" name="artifact" upperBound="-1"
          eType="#//artifacts/AbstractArtifact" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FileArtifact" abstract="true" eSuperTypes="#//aux/Nameable #//artifacts/AbstractArtifact">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="file" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Base64Binary"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="localFilePath" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractArtifact" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="QuestionnaireInner" eSuperTypes="#//artifacts/AbstractArtifact #//aux/Nameable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elements" lowerBound="1"
          upperBound="-1" eType="#//artifacts/questionnaire/ElementaryComponent" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="placementquestionnaire"
          lowerBound="1" eType="#//taskDescription/QuestionnaireMeasurement" eOpposite="#//taskDescription/QuestionnaireMeasurement/questionnaire"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProjectIDE" abstract="true" eSuperTypes="#//artifacts/AbstractArtifact">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectName" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompilationUnit" abstract="true" eSuperTypes="#//artifacts/FileArtifact"/>
    <eClassifiers xsi:type="ecore:EClass" name="PdfFIle" eSuperTypes="#//artifacts/FileArtifact"/>
    <eClassifiers xsi:type="ecore:EClass" name="JavaProject" eSuperTypes="#//artifacts/ProjectIDE">
      <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
          eType="#//artifacts/JavaCompUnit" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="otherFiles" upperBound="-1"
          eType="#//artifacts/OtherFile" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredLibrary" upperBound="-1"
          eType="#//artifacts/Library" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JavaCompUnit" eSuperTypes="#//artifacts/CompilationUnit">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="package" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OtherFile" eSuperTypes="#//artifacts/FileArtifact">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="folder" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Library" eSuperTypes="#//artifacts/FileArtifact"/>
    <eSubpackages name="questionnaire" nsURI="questionnaire" nsPrefix="questionnaire">
      <eClassifiers xsi:type="ecore:EClass" name="ElementaryComponent" abstract="true"
          eSuperTypes="#//artifacts/questionnaire/Labelable">
        <eStructuralFeatures xsi:type="ecore:EReference" name="restriction" eType="#//artifacts/questionnaire/Restriction"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="#//artifacts/questionnaire/ElementaryComponent">
        <eStructuralFeatures xsi:type="ecore:EReference" name="chidren" lowerBound="1"
            upperBound="-1" eType="#//artifacts/questionnaire/ElementaryComponent"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Question" abstract="true" eSuperTypes="#//artifacts/questionnaire/ElementaryComponent"/>
      <eClassifiers xsi:type="ecore:EClass" name="TextField" eSuperTypes="#//artifacts/questionnaire/Question"/>
      <eClassifiers xsi:type="ecore:EClass" name="ComposedQuestion" abstract="true"
          eSuperTypes="#//artifacts/questionnaire/Question">
        <eStructuralFeatures xsi:type="ecore:EReference" name="choice" lowerBound="2"
            upperBound="-1" eType="#//artifacts/questionnaire/Choice" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Choice" eSuperTypes="#//artifacts/questionnaire/Labelable"/>
      <eClassifiers xsi:type="ecore:EClass" name="SimpleChoice" eSuperTypes="#//artifacts/questionnaire/ComposedQuestion"/>
      <eClassifiers xsi:type="ecore:EClass" name="MultiChoice" eSuperTypes="#//artifacts/questionnaire/ComposedQuestion">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Restriction" abstract="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="AppendableElement" eSuperTypes="#//artifacts/questionnaire/Restriction">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultQuantity" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//IntObject"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DependentElement" eSuperTypes="#//artifacts/questionnaire/Restriction">
        <eStructuralFeatures xsi:type="ecore:EReference" name="question" lowerBound="1"
            eType="#//artifacts/questionnaire/Question"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="expectedValue" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Labelable" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="content" lowerBound="1"
            upperBound="-1" eType="#//artifacts/questionnaire/Content" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Content">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="aux" nsURI="aux" nsPrefix="aux">
    <eClassifiers xsi:type="ecore:EClass" name="Nameable" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
