<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="decode" nsURI="http://www.example.org/modelDecode" nsPrefix="modelDecode">
  <eClassifiers xsi:type="ecore:EClass" name="CodingExperiment" eSuperTypes="#//aux/Nameable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="task" lowerBound="1" eType="#//taskDescription/ModeledTask"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="measurements" lowerBound="1"
        eType="#//measurement/Measurements" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedArtefacts" lowerBound="1"
        eType="#//artifacts/ProvidedArtefacts" containment="true"/>
  </eClassifiers>
  <eSubpackages name="taskDescription" nsURI="taskDescription" nsPrefix="taskDescription">
    <eClassifiers xsi:type="ecore:EClass" name="ModeledTask" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="restriction" eType="#//taskDescription/Restriction"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Sequencial" eSuperTypes="#//taskDescription/ComposedTask">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
          eType="#//taskDescription/ModeledTask" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Random" eSuperTypes="#//taskDescription/ComposedTask">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" ordered="false"
          upperBound="-1" eType="#//taskDescription/ModeledTask" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComposedTask" abstract="true" eSuperTypes="#//taskDescription/ModeledTask"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExperimentalTask" eSuperTypes="#//taskDescription/ModeledTask #//aux/Nameable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="newAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//BooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredArtifacts" upperBound="-1"
          eType="#//artifacts/AbstractArtifact"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="depends" upperBound="-1"
          eType="#//taskDescription/ExperimentalTask"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Restriction">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="deadline" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//DateTime"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeFrame" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="artifacts" nsURI="artifacts" nsPrefix="artifacts">
    <eClassifiers xsi:type="ecore:EClass" name="AtomicArtifact" eSuperTypes="#//artifacts/AbstractArtifact">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//artifacts/ArtifactType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ArtifactType">
      <eLiterals name="Code"/>
      <eLiterals name="Test" value="1"/>
      <eLiterals name="Description" value="2"/>
      <eLiterals name="Design" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProvidedArtefacts">
      <eStructuralFeatures xsi:type="ecore:EReference" name="artifact" upperBound="-1"
          eType="#//artifacts/AbstractArtifact" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComplexArtifact" eSuperTypes="#//artifacts/AbstractArtifact">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//artifacts/ComplexArtifactType"
          defaultValueLiteral="Project"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ComplexArtifactType">
      <eLiterals name="Project"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractArtifact" abstract="true"
        eSuperTypes="#//aux/Nameable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="artifactDomain" eType="#//artifacts/ArtifactLanguage"
          defaultValueLiteral="Common"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="file" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Base64Binary"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="localFilePath" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ArtifactLanguage">
      <eLiterals name="Java"/>
      <eLiterals name="Common" value="1"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="measurement" nsURI="measurement" nsPrefix="measurement">
    <eClassifiers xsi:type="ecore:EClass" name="Measurements">
      <eStructuralFeatures xsi:type="ecore:EReference" name="measurements" lowerBound="1"
          upperBound="-1" eType="#//measurement/AbstractMeasurement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Survey" eSuperTypes="#//measurement/AbstractMeasurement"/>
    <eClassifiers xsi:type="ecore:EClass" name="TimeOnTask" eSuperTypes="#//measurement/AbstractMeasurement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="relatedTask" upperBound="-1"
          eType="#//taskDescription/ModeledTask"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ObservingArtifact" abstract="true"
        eSuperTypes="#//measurement/AbstractMeasurement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="aspect" lowerBound="1"
          eType="#//measurement/AspectObserved" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ObservingProvidedArtifact" eSuperTypes="#//measurement/ObservingArtifact">
      <eStructuralFeatures xsi:type="ecore:EReference" name="observedArtifact" lowerBound="1"
          eType="#//artifacts/AtomicArtifact"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ObservingProducedArtifact" eSuperTypes="#//measurement/ObservingArtifact"/>
    <eClassifiers xsi:type="ecore:EClass" name="ObservingAllArtifacts" eSuperTypes="#//measurement/ObservingArtifact"/>
    <eClassifiers xsi:type="ecore:EClass" name="AspectObserved" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Edition" eSuperTypes="#//measurement/AspectObserved"/>
    <eClassifiers xsi:type="ecore:EClass" name="Execution" eSuperTypes="#//measurement/AspectObserved"/>
    <eClassifiers xsi:type="ecore:EClass" name="Testing" eSuperTypes="#//measurement/Execution">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ObservePassedTest" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//BooleanObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractMeasurement" abstract="true"
        eSuperTypes="#//aux/Nameable"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnyAction" eSuperTypes="#//measurement/AspectObserved"/>
  </eSubpackages>
  <eSubpackages name="aux" nsURI="aux" nsPrefix="aux">
    <eClassifiers xsi:type="ecore:EClass" name="Nameable" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
